import { z } from 'zod';

export const NotificationTypeSchema = z.enum(['TASK_ASSIGNED','TASK_COMPLETED','TASK_REVIEWED','TASK_REVISION_REQUESTED','PROPOSAL_CREATED','PROPOSAL_VOTED','PROPOSAL_PASSED','PROPOSAL_REJECTED','PROPOSAL_EXECUTED','ACHIEVEMENT_EARNED','LEVEL_UP','STREAK_MILESTONE','TOKEN_RECEIVED','TOKEN_VESTED','ESCROW_FUNDED','ESCROW_RELEASED','PROJECT_INVITATION','PROJECT_UPDATE','PROJECT_FUNDED','COMMENT_REPLY','MENTION','FOLLOWER_NEW','SYSTEM_ANNOUNCEMENT','SECURITY_ALERT']);

export type NotificationTypeType = `${z.infer<typeof NotificationTypeSchema>}`

export default NotificationTypeSchema;
