"""
Pitch Generation Workflow

LangGraph StateGraph that orchestrates end-to-end project pitch generation
from a single prompt. Chains multiple CrewAI crews and optionally generates
a Gamma pitch deck.

Graph:
    [START] → parse_prompt → concept_crew → strategy_crew → positioning_crew
           → assemble_project → route_deck
                                 ├→ generate_deck (if requested)
                                 └→ skip_deck
           → finalize → [END]

Split endpoints allow using individual phases:
    - /pitch/generate: Full end-to-end pipeline
    - /pitch/enhance: Start from partial data, fill gaps
    - /pitch/deck: Generate deck from existing project data
"""

from __future__ import annotations

from typing import Any, Literal

from ..core.graph_builder import GraphBuilder
from ..core.state import PitchGenerationState


# ── Node Functions ──────────────────────────────────────────────────────


async def parse_prompt(state: PitchGenerationState) -> dict[str, Any]:
    """Parse and normalize the input prompt.

    For enhance mode, merges partial_data into state so downstream
    crews can skip already-filled fields.
    """
    partial = state.get("partial_data") or {}
    updates: dict[str, Any] = {}

    # Carry forward any pre-filled fields from partial data
    for field in [
        "title", "problem_statement", "solution", "categories",
        "project_type", "duration", "milestones", "resources",
        "tags", "target_audience", "expected_impact", "description",
    ]:
        if field in partial and partial[field]:
            updates[field] = partial[field]

    return updates


async def run_concept_crew(state: PitchGenerationState) -> dict[str, Any]:
    """Execute the concept crew to generate title, problem, solution, categories.

    Skips if these fields are already populated (enhance mode).
    """
    # Check if concept is already provided
    if (
        state.get("title")
        and state.get("problem_statement")
        and state.get("solution")
        and state.get("categories")
    ):
        return {}  # Already have concept data, skip

    # TODO: Build and kick off concept crew when LLM is configured
    # crew = build_concept_crew(agent_builder)
    # result = await run_crew_async(crew, inputs={"prompt": state["prompt"]})
    # return parse_concept_result(result)

    prompt = state.get("prompt", "")
    return {
        "title": f"[Generated] Project from: {prompt[:50]}...",
        "problem_statement": (
            "This project addresses a problem described in the user's prompt. "
            "Full analysis pending agent implementation."
        ),
        "solution": (
            "The proposed solution will be generated by the concept architect agent. "
            "Pending agent implementation."
        ),
        "categories": ["TECHNOLOGY"],
        "project_type": "PRODUCT",
        "duration": "THREE_SIX_MONTHS",
    }


async def run_strategy_crew(state: PitchGenerationState) -> dict[str, Any]:
    """Execute the strategy crew to generate milestones, resources, timeline.

    Skips if milestones and resources are already populated.
    """
    if state.get("milestones") and state.get("resources"):
        return {}

    # TODO: Build and kick off strategy crew
    # crew = build_strategy_crew(agent_builder)
    # result = await run_crew_async(crew, inputs={...})

    return {
        "milestones": [
            {
                "title": "Project Kickoff",
                "description": "Initialize project infrastructure and team",
                "target_date": "2026-03-01",
            },
            {
                "title": "MVP Development",
                "description": "Build and test minimum viable product",
                "target_date": "2026-05-01",
            },
            {
                "title": "Beta Launch",
                "description": "Launch beta version to early adopters",
                "target_date": "2026-07-01",
            },
            {
                "title": "Public Launch",
                "description": "Full public release with marketing campaign",
                "target_date": "2026-08-01",
            },
        ],
        "resources": [
            {
                "name": "Development Team",
                "description": "Core developers for building the product",
                "quantity": 2,
                "estimated_cost": 20000,
                "is_required": True,
            },
            {
                "name": "Cloud Infrastructure",
                "description": "Hosting and deployment services",
                "quantity": 1,
                "estimated_cost": 3000,
                "is_required": True,
            },
            {
                "name": "Design Assets",
                "description": "UI/UX design and branding",
                "quantity": 1,
                "estimated_cost": 5000,
                "is_required": False,
            },
        ],
        "timeline": "Estimated 6-month timeline from kickoff to public launch.",
    }


async def run_positioning_crew(state: PitchGenerationState) -> dict[str, Any]:
    """Execute the positioning crew for tags, audience, impact, description.

    Skips if positioning data is already populated.
    """
    if (
        state.get("tags")
        and state.get("target_audience")
        and state.get("description")
    ):
        return {}

    # TODO: Build and kick off positioning crew

    title = state.get("title", "Untitled Project")
    return {
        "tags": ["technology", "innovation", "open-source"],
        "target_audience": (
            "Developers, entrepreneurs, and early adopters interested in "
            "collaborative project building."
        ),
        "expected_impact": (
            "This project aims to demonstrate a new approach to collaborative "
            "project development. Impact metrics pending agent implementation."
        ),
        "description": (
            f"{title} is a project generated from a single prompt using AI-powered "
            "pitch generation. The full description will be crafted by the "
            "description writer agent once configured."
        ),
    }


async def assemble_project(state: PitchGenerationState) -> dict[str, Any]:
    """Assemble all crew outputs into the final project data structure.

    This produces the complete project payload that matches the
    .NET backend CreateProjectDto format.
    """
    project_data = {
        "title": state.get("title", ""),
        "description": state.get("description", ""),
        "problemStatement": state.get("problem_statement", ""),
        "solution": state.get("solution", ""),
        "categories": state.get("categories", []),
        "projectType": state.get("project_type", "PRODUCT"),
        "duration": state.get("duration"),
        "targetAudience": state.get("target_audience"),
        "expectedImpact": state.get("expected_impact"),
        "timeline": state.get("timeline"),
        "tags": ", ".join(state.get("tags", [])),
        "milestones": state.get("milestones", []),
        "resources": state.get("resources", []),
    }

    return {"project_data": project_data}


def route_deck(
    state: PitchGenerationState,
) -> Literal["generate_deck", "skip_deck"]:
    """Route: generate a Gamma pitch deck or skip."""
    return "generate_deck" if state.get("generate_deck") else "skip_deck"


async def generate_deck(state: PitchGenerationState) -> dict[str, Any]:
    """Generate a Gamma pitch deck from the assembled project data.

    Uses the Gamma API to create a presentation. Returns the URL
    if successful, or a message if the API key is not configured.
    """
    # TODO: Use GammaGenerateTool when API key is configured
    # Build a rich prompt from the project data for Gamma
    project = state.get("project_data", {})
    title = project.get("title", "Untitled")

    # Compose pitch content for Gamma
    pitch_content = f"""
Project: {title}

Problem:
{project.get('problemStatement', '')}

Solution:
{project.get('solution', '')}

Target Audience:
{project.get('targetAudience', '')}

Expected Impact:
{project.get('expectedImpact', '')}

Milestones:
"""
    for m in project.get("milestones", []):
        pitch_content += f"- {m.get('title', '')}: {m.get('description', '')} (Target: {m.get('target_date', '')})\n"

    pitch_content += "\nResources Needed:\n"
    for r in project.get("resources", []):
        cost = r.get("estimated_cost", 0)
        pitch_content += f"- {r.get('name', '')}: ${cost:,.0f}\n"

    return {
        "deck_url": "",
        "deck_generation_id": "",
        # The pitch_content would be passed to GammaGenerateTool._run()
        # Stub response until API key is configured:
        "result": {
            **_build_result(state),
            "deck": {
                "status": "pending_configuration",
                "message": "Gamma API key not configured. Set GAMMA_API_KEY to enable.",
                "pitch_content_preview": pitch_content[:500],
            },
        },
    }


async def skip_deck(state: PitchGenerationState) -> dict[str, Any]:
    """Skip deck generation, just pass through."""
    return {}


async def finalize(state: PitchGenerationState) -> dict[str, Any]:
    """Finalize the pitch generation result.

    If result was already set by generate_deck, just return.
    Otherwise, build the result without deck info.
    """
    if state.get("result"):
        return {}

    return {"result": _build_result(state)}


def _build_result(state: PitchGenerationState) -> dict[str, Any]:
    """Build the API response from the current state."""
    project = state.get("project_data", {})
    return {
        "project": project,
        "metadata": {
            "prompt": state.get("prompt", ""),
            "phases_completed": [
                "concept",
                "strategy",
                "positioning",
                "assembly",
            ],
        },
    }


# ── Graph Construction ──────────────────────────────────────────────────


def build_pitch_generation_graph() -> Any:
    """Build and compile the pitch generation LangGraph workflow.

    Returns:
        Compiled StateGraph supporting ainvoke() and astream().
    """
    graph = (
        GraphBuilder(PitchGenerationState)
        .add_function_node("parse_prompt", parse_prompt)
        .add_function_node("concept_crew", run_concept_crew)
        .add_function_node("strategy_crew", run_strategy_crew)
        .add_function_node("positioning_crew", run_positioning_crew)
        .add_function_node("assemble", assemble_project)
        .add_function_node("generate_deck", generate_deck)
        .add_function_node("skip_deck", skip_deck)
        .add_function_node("finalize", finalize)
        # Linear flow through crews
        .set_entry("parse_prompt")
        .add_edge("parse_prompt", "concept_crew")
        .add_edge("concept_crew", "strategy_crew")
        .add_edge("strategy_crew", "positioning_crew")
        .add_edge("positioning_crew", "assemble")
        # Conditional deck generation
        .add_router("assemble", route_deck, {
            "generate_deck": "generate_deck",
            "skip_deck": "skip_deck",
        })
        .add_edge("generate_deck", "finalize")
        .add_edge("skip_deck", "finalize")
        .add_terminal("finalize")
        .build()
    )

    return graph


# Compile at module level
pitch_generation_graph = build_pitch_generation_graph()


# ── Deck-only Graph ────────────────────────────────────────────────────


def build_deck_only_graph() -> Any:
    """Build a minimal graph just for generating a deck from existing project data.

    Used by the /pitch/deck endpoint.
    """
    graph = (
        GraphBuilder(PitchGenerationState)
        .add_function_node("assemble", assemble_project)
        .add_function_node("generate_deck", generate_deck)
        .add_function_node("finalize", finalize)
        .set_entry("assemble")
        .add_edge("assemble", "generate_deck")
        .add_edge("generate_deck", "finalize")
        .add_terminal("finalize")
        .build()
    )

    return graph


deck_only_graph = build_deck_only_graph()
