// Auto-generated by generate-csharp-models.ts - DO NOT EDIT manually
// Contains composite indexes and relationship configurations that require Fluent API
using Microsoft.EntityFrameworkCore;
using ArdaNova.Domain.Models.Entities;

namespace ArdaNova.Infrastructure.Data;

public static class GeneratedModelConfigurations
{
    /// <summary>
    /// Applies generated model configurations (composite indexes, bidirectional FK disambiguation).
    /// </summary>
    public static void ApplyGeneratedConfigurations(this ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Account>().HasIndex(e => new { e.provider, e.providerAccountId }).IsUnique();
        modelBuilder.Entity<UserAchievement>().HasIndex(e => new { e.userId, e.achievementId }).IsUnique();
        modelBuilder.Entity<LeaderboardEntry>().HasIndex(e => new { e.leaderboardId, e.userId }).IsUnique();
        modelBuilder.Entity<ProjectComment>().HasIndex(e => new { e.targetType, e.targetId });
        modelBuilder.Entity<ProjectMember>().HasIndex(e => new { e.projectId, e.userId }).IsUnique();
        modelBuilder.Entity<GuildMember>().HasIndex(e => new { e.guildId, e.userId }).IsUnique();
        modelBuilder.Entity<MembershipCredential>().HasIndex(e => new { e.projectId, e.userId }).IsUnique();
        modelBuilder.Entity<MembershipCredential>().HasIndex(e => new { e.guildId, e.userId }).IsUnique();
        modelBuilder.Entity<WalletVerificationChallenge>().HasIndex(e => new { e.walletId, e.consumedAt });
        modelBuilder.Entity<WalletVerificationChallenge>().HasIndex(e => new { e.userId, e.expiresAt });
        modelBuilder.Entity<ConversationMember>().HasIndex(e => new { e.conversationId, e.userId }).IsUnique();
        modelBuilder.Entity<ChatMessage>().HasIndex(e => new { e.conversationId, e.sentAt });
        modelBuilder.Entity<EventAttendee>().HasIndex(e => new { e.eventId, e.userId }).IsUnique();
        modelBuilder.Entity<EventCoHost>().HasIndex(e => new { e.eventId, e.userId }).IsUnique();
        modelBuilder.Entity<UserFollow>().HasIndex(e => new { e.followerId, e.followingId }).IsUnique();
        modelBuilder.Entity<ProjectFollow>().HasIndex(e => new { e.userId, e.projectId }).IsUnique();
        modelBuilder.Entity<GuildFollow>().HasIndex(e => new { e.userId, e.guildId }).IsUnique();
        modelBuilder.Entity<OpportunityApplication>().HasIndex(e => new { e.opportunityId, e.applicantId }).IsUnique();
        modelBuilder.Entity<OpportunityBid>().HasIndex(e => new { e.opportunityId, e.bidderId }).IsUnique();
        modelBuilder.Entity<KycSubmission>().HasIndex(e => new { e.userId, e.status });
        modelBuilder.Entity<KycDocument>().HasIndex(e => new { e.submissionId, e.type }).IsUnique();
        modelBuilder.Entity<TokenBalance>().HasIndex(e => new { e.userId, e.projectTokenConfigId, e.holderClass }).IsUnique();
        modelBuilder.Entity<ProjectInvestment>().HasIndex(e => new { e.projectTokenConfigId, e.userId });
        modelBuilder.Entity<StripeWebhookEvent>().HasIndex(e => new { e.status, e.processingLeaseExpiresAt });
        modelBuilder.Entity<EconomicSettlement>().HasIndex(e => new { e.beneficiaryUserId, e.status });
        modelBuilder.Entity<EconomicSettlement>().HasIndex(e => new { e.projectId, e.status });
        modelBuilder.Entity<EconomicSettlement>().HasIndex(e => new { e.taskId, e.kind });
        modelBuilder.Entity<EconomicOutbox>().HasIndex(e => new { e.status, e.availableAt });
        modelBuilder.Entity<FundingIntent>().HasIndex(e => new { e.funderUserId, e.idempotencyKey }).IsUnique();
        modelBuilder.Entity<FundingIntent>().HasIndex(e => new { e.funderUserId, e.status });
        modelBuilder.Entity<FundingIntent>().HasIndex(e => new { e.projectId, e.status });
        modelBuilder.Entity<FundingIntent>().HasIndex(e => new { e.projectTokenConfigId, e.status });
        modelBuilder.Entity<TaskCommerceAgreement>().HasIndex(e => new { e.contributorUserId, e.status });
        modelBuilder.Entity<TaskCommerceAgreement>().HasIndex(e => new { e.projectId, e.status });
        modelBuilder.Entity<AssetDefinition>().HasIndex(e => new { e.chainType, e.chainNetwork, e.canonicalAssetId }).IsUnique();
        modelBuilder.Entity<ProjectTokenPolicy>().HasIndex(e => new { e.projectId, e.version }).IsUnique();
        modelBuilder.Entity<EquityOrRedemptionRightPolicy>().HasIndex(e => new { e.projectId, e.kind, e.version }).IsUnique();
        modelBuilder.Entity<EligibilityDecision>().HasIndex(e => new { e.userId, e.equityOrRedemptionRightPolicyId, e.status });

        // Bidirectional FK disambiguation
        // ProjectTask.opportunityId -> Opportunity
        modelBuilder.Entity<ProjectTask>()
            .HasOne(e => e.Opportunity)
            .WithMany(e => e.ProjectTasks)
            .HasForeignKey(e => e.opportunityId)
            .OnDelete(DeleteBehavior.SetNull);

        // Opportunity.taskId -> ProjectTask
        modelBuilder.Entity<Opportunity>()
            .HasOne(e => e.Task)
            .WithMany(e => e.Opportunities)
            .HasForeignKey(e => e.taskId)
            .OnDelete(DeleteBehavior.Cascade);

    }
}
