// Auto-generated by generate-csharp-models.ts - DO NOT EDIT manually
// Contains composite index configurations that require Fluent API
using Microsoft.EntityFrameworkCore;
using ArdaNova.Domain.Models.Entities;

namespace ArdaNova.Infrastructure.Data;

public static class GeneratedModelConfigurations
{
    /// <summary>
    /// Applies generated model configurations (composite indexes).
    /// </summary>
    public static void ApplyGeneratedConfigurations(this ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ConversationMember>().HasIndex(e => new { e.conversationId, e.userId }).IsUnique();
        modelBuilder.Entity<ChatMessage>().HasIndex(e => new { e.conversationId, e.sentAt });
        modelBuilder.Entity<OpportunityApplication>().HasIndex(e => new { e.opportunityId, e.applicantId }).IsUnique();
    }
}
